# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
# init-frame.org
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2012/03/15 06:30:18$
#
# Author: Youhei SASAKI <uwabami@gfd-dennou.org>
# License: Expat
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#+SETUPFILE: ~/.emacs.d/template/org/level-2.org
#+INCLUDE: ~/.emacs.d/template/org/menu-level-2.org
#+TITLE: 03.GUI 環境でのフレームの設定
#Code:


** 背景色の設定
color-theme では透過色のターミナルで作業することを考えて,
意図的に背景色を設定していない. なので, ここで設定する.
#+BEGIN_SRC emacs-lisp
  (when window-system
    (add-to-list 'default-frame-alist '(background-color . "#242424")))
#+END_SRC
** [[http://d.hatena.ne.jp/khiker/20090809/emacs_opacity][フレームを半透明にする]]
#+BEGIN_SRC emacs-lisp
  (defun my-opacity-change (action)
    (let* ((op
            (frame-parameter
             (selected-frame) 'alpha)) val)
      (unless op
        (setq op 100))
      (when (setq val
                  (cond
                   ((eq action 'up)
                    (if (> op 90) 100 (+ op 10)))
                   ((eq action 'down)
                    (if (> 10 op) 10 (- op 10)))
                   ((eq action 'clear) 100)
                   ((numberp action) action)
                   (t nil)))
        (set-frame-parameter (selected-frame) 'alpha val))))
  (when window-system
    (my-opacity-change 90)     ; default の透明度は 90 に
    )
#+END_SRC
** フォント設定
   Ricty を使用することにする(Ricty の無い環境はとりあえず考えていない).
#+BEGIN_SRC emacs-lisp
  (create-fontset-from-ascii-font "Ricty-18" nil "ricty")
  (dolist (charset '(
                     unicode
                     japanese-jisx0208
                     japanese-jisx0208-1978
                     japanese-jisx0212
                     japanese-jisx0213-1
                     japanese-jisx0213-2
                     japanese-jisx0213-a
                     japanese-jisx0213.2004-1
                     katakana-jisx0201
                     ))
    (set-fontset-font "fontset-ricty"
                      charset
                      (font-spec :family "Ricty" :size 18 nil 'prepend)))
  (add-to-list 'default-frame-alist '(font ."fontset-ricty"))
  (custom-set-faces
   '(variable-pitch ((t (:family "Ricty" :size 18 nil 'prepend)))))
#+END_SRC
