# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#+begin_quote
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2011/12/02 16:01:49$
#
# Author: Youhei SASAKI <uwabami@gfd-dennou.org>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#+end_quote
#+TITLE: autoinsert の設定
#+OPTIONS: toc:2 num:nil ^:nil
#Code:

** よくある設定
*** 初期設定
#+begin_src emacs-lisp
(require 'autoinsert)
(auto-insert-mode 1)
#+end_src
*** insert 時に問い合わせない
#+begin_src emacs-lisp
  (setq auto-insert-query nil)
#+end_src
*** テンプレートディレクトリの設定
- テンプレートとなるファイルがあるディレクトリ
- 末尾に"/"が必要なので注意
#+begin_src emacs-lisp
(setq auto-insert-directory "~/.emacs.d/template/")
#+end_src
*** add-hook
#+begin_src emacs-lisp
(add-hook 'find-file-hooks 'auto-insert)
#+end_src

** テンプレート内の置換変数の設定/置換関数の定義
*** 置換する変数
- author, email, file名 を展開する
- user-full-name, user-mail-address を設定しておくこと
#+begin_src emacs-lisp
(defvar my-template-replacements-alist
  '(("%file%" .
     (lambda()
       (file-name-nondirectory (buffer-file-name))))
    ("%author%" . (lambda()(identity user-full-name)))
    ("%email%"  . (lambda()(identity user-mail-address)))
    ("%filewithoutext%" .
     (lambda()
       (file-name-sans-extension (file-name-nondirectory (buffer-file-name)))))
    ))
#+end_src
*** 置換関数
#+begin_src emacs-lisp
(defun my-template ()
  (time-stamp)
  (mapc #'(lambda(c)
             (progn
               (goto-char (point-min))
               (replace-string (car c) (funcall (cdr c)) nil)))
           my-template-replacements-alist)
  (goto-char (point-max))
  (message "done."))
#+end_src
** TODO テンプレートの設定[0/1]
- [ ] org の場合, ディレクトリに合わせてテンプレートを切り替えたい
#+begin_src emacs-lisp
  (setq auto-insert-alist
        (nconc '(
                 ("\\.el$"   . ["template.el"   my-template])
                 ("\\.rb$"   . ["template.rb"   my-template])
                 ("\\.rab$"  . ["template.rab"  my-template])
                 ("\\.zsh$"  . ["template.zsh"  my-template])
                 ("\\.sh$"   . ["template.sh"   my-template])
                 ("\\.f90$"  . ["template.f90"  my-template])
                 ("\\.cpp$"  . ["template.cpp"  my-template])
                 ("\\.tex$"  . ["template.tex"  my-template])
  ;;               ("\\.org$"  . ["template.org"  my-template])
                 ("\\.muse$" . ["template.muse" my-template])
                 ) auto-insert-alist))
#+end_src

