# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
# 30wl.org
#+begin_quote
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2011/11/28 13:16:12$
#
# Author: Youhei SASAKI <uwabami@gfd-dennou.org>
# License: GPL-3+
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#+end_quote
#+SETUPFILE: ~/.emacs.d/template/org/level-2.org
#+INCLUDE: ~/.emacs.d/template/org/menu-level-2.org
#+TITLE: 06. Wanderlust の設定
#Code:

** TODO HTML メールの表示[0/1]

- w3m を使う.
- [ ] w3m-el で外部リンクを踏む際に safe にする設定が良くわからない...Orz
#+begin_src emacs-lisp
(when (locate-library "mime-setup")
  (setq mime-setup-enable-inline-html t)
  (require 'mime-setup))
(when (locate-library "w3m-load")
  (require 'w3m-ems)
  (require 'w3m-load)
  (require 'mime-w3m)
  )
#+end_src

** デフォルトのメーラを Wanderlust に変更する

#+begin_src emacs-lisp
(autoload 'wl "wl" "Wanderlust" t)
(autoload 'wl-other-frame "wl" "Wanderlust on new frame" t)
(autoload 'wl-draft "wl-draft" "Write draft with Wanderlust." t)
(if (boundp 'mail-user-agent)
    (setq mail-user-agent 'wl-user-agent))
(if (boundp 'read-mail-command)
  (setq read-mail-command 'wl))
(if (fboundp 'define-mail-user-agent)
  (define-mail-user-agent
    'wl-user-agent
    'wl-user-agent-compose
    'wl-draft-send
    'wl-draft-kill
    'mail-send-hook))
#+end_src

** キーバインド. F3 で Wanderlust を起動

#+begin_src emacs-lisp
(global-set-key [f3] 'wl)
#+end_src

** Wanderlust 本体の設定は基本外部ファイルで
#+begin_src emacs-lisp
(setq wl-init-file "~/.wl/init.gpg")
#+end_src
