# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#init-muse.org
#+begin_quote
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2011/11/29 16:18:57$
#
# Author: Youhei SASAKI <uwabami@gfd-dennou.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#+end_quote
#Code:
#+TITLE: MuseMode の設定
#+OPTIONS: toc:2 num:nil ^:nil

** 読み込み
*** 読み込み
#+BEGIN_SRC emacs-lisp
  (when (not (locate-library "htmlize"))
    (add-to-load-path "site-lisp/org-mode/contrib/lisp/")
    (eval-when-compile (add-to-load-path "site-lisp/org-mode/contrib/lisp/")))
  (when (not (locate-library "muse"))
    (add-to-load-path "site-lisp/muse-el/lisp")
    (eval-when-compile (add-to-load-path "site-lisp/muse-el/lisp")))
  (require 'htmlize)
  (require 'muse-mode)
  (require 'muse-html)
  (require 'muse-latex)
  (require 'muse-latex2png)
  (require 'muse-project)
  (require 'muse-wiki)
  (require 'muse-colors)
#+END_SRC
** キーバインドの設定
*** C-x n で project-find-file
#+BEGIN_SRC emacs-lisp
(define-key ctl-x-map "n" 'muse-project-find-file)
#+END_SRC
*** outline-minor-mode を有効化して TAB に割り当て
#+BEGIN_SRC emacs-lisp
  (add-hook 'muse-mode-hook
            (lambda ()
              (footnote-mode)
              (outline-minor-mode)
              (if window-system
                  (define-key muse-mode-map [tab] 'outline-toggle-children)
                (define-key muse-mode-map "\t" 'outline-toggle-children))
              ))
#+END_SRC
** 文字コード関連
#+BEGIN_SRC emacs-lisp
(setq muse-xhtml-charset-default "utf-8")
(setq muse-html-encoding-default (quote utf-8))
(setq muse-html-meta-content-encoding (quote utf-8))
#+END_SRC
** Project の定義
   cc-env にしか使わないので, その設定のみ
*** style
#+BEGIN_SRC emacs-lisp
(muse-derive-style "my:cc-env" "xhtml"
                   :author "Youhei SASAKI <uwabami@gfd-dennou.org>"
                   :style-sheet "../css/cc-env.css"
                   :header "~/.emacs.d/template/muse/cc-env-header.html"
                   :footer "~/.emacs.d/template/muse/cc-env-footer.html"
                   :base-url "http://www.gfd-dennou.org/member/uwabami/cc-env/"
                   )
(setq muse-footer-date-format "%F %H:%M:%S %Z ")
#+END_SRC
*** Project
#+BEGIN_SRC emacs-lisp
(setq muse-project-alist
     '(
       ("cc-env"
        ("~/Public/cc-env" :default "index")
        (:base "my:cc-env" :path "~/Public/cc-env")
        ))
     )
#+END_SRC
