# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
# init-org.org
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2012/01/04 18:12:42$
#
# Author: Youhei SASAKI <uwabami@gfd-dennou.org>
# License: Expat
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#+SETUPFILE: ~/.emacs.d/template/org/level-2.org
#+INCLUDE: ~/.emacs.d/template/org/menu-level-2.org
#+TITLE: org-mode の設定

* 基本設定
   ~/.emacs.d/init.el でも読み込んでいるけれど, ここでも有効にする.
#+BEGIN_SRC emacs-lisp
  (require 'org-install)
  (require 'org)
  ;; 打ち切らない.
  (setq org-startup-truncated nil)
  ;; ファイルを開く時は項目を折り畳んだ状態にする
  (setq org-startup-folded t)
  ;; 開いた時に画像を inline で表示しない
  (setq org-startup-with-inline-images nil)
  ;; link を return で追う
  (setq org-retrun-follows-link t)
  ;; フォントロックを有効に
  (add-hook 'org-mode-hook 'turn-on-font-lock)
  ;; 基本ディレクトリ
  (setq org-directory "~/Documents/Dropbox/org/")
  ;; Agenda
  (setq org-default-notes-file (concat org-directory "remember.org"))
  ;; (when (locate-library "remember-el")
  ;;   (setq remember-annotation-functions '(org-remember-annotation))
  ;;   (setq remember-handler-functions '(org-remember-handler))
  ;;   (setq org-remember-templates
  ;;         '(("Todo" ?t "** TODO %?\n   %i\n   %a\n   %t" nil "Inbox")
  ;;           ("Bug" ?b "** TODO %?   :bug:\n   %i\n   %a\n   %t" nil "Inbox")
  ;;           ("Idea" ?i "** %?\n   %i\n   %a\n   %t" nil "New Ideas")
  ;;           )))
#+END_SRC

* 補完の追加
  githubはコードブロックを大文字で認識するので, <s を大文字に
#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-structure-template-alist
               '("s" "#+BEGIN_SRC ?\n\n#+END_SRC"
                     "<src lang=\"?\">\n\n</src>"))
#+END_SRC
* キーマップの設定
   デフォルトの org のキーバインドはあまりにも多くのキーバインドを書き換えるので
   かなりアレ. 必要なモンだけ有効にしておく.
   @see [[http://d.hatena.ne.jp/kitokitoki/20100430/p1][org-mode のデフォルトのキーバインドを無効にして必要なものだけ再定義する]]
#+BEGIN_SRC emacs-lisp
  ;; (add-hook 'org-mode-hook
  ;;   (lambda()
  ;;     ;; clear all org-map
  ;;     (setq org-goto-map (make-keymap))
  ;;     (setq org-agenda-mode-map (make-keymap))
  ;;     (setq org-cdlatex-mode-map (make-keymap))
  ;;     (setq org-exit-edit-mode-map (make-keymap))
  ;;     (setq org-goto-local-auto-isearch-map (make-keymap))
  ;;     (setq org-mode-map (make-keymap))
  ;;     (setq org-mouse-map (make-keymap))
  ;;     (setq orgstruct-mode-map (make-keymap))
  ;;     (setq my-org-mode-map (make-keymap))
  ;;     (use-local-map my-org-mode-map)
  ;;     ;; 自分の使いたい機能だけを設定していく
  ;;     (define-key my-org-mode-map (kbd "TAB") 'org-cycle)
  ;;     (define-key my-org-mode-map (kbd "C-c C-c") 'org-toggle-checkbox)
  ;;     (define-key my-org-mode-map (kbd "C-c \'") 'org-edit-src-code)
  ;;     (define-key my-org-mode-map (kbd "C-c C-e") 'org-export)
  ;;     (define-key my-org-mode-map (kbd "C-c C-l") 'org-insert-link)
  ;; ))
#+END_SRC
* MobileOrg の設定
#+BEGIN_SRC emacs-lisp
  (require 'org-mobile)
  (setq org-mobile-directory "~/Documents/Dropbox/MobileOrg")
  (setq org-mobile-inbox-for-pull "~/Documents/Dropbox/org/remember.org")
#+END_SRC
* HTML export の設定
   HTML に export する設定. Project の使い方がまだイマイチ
#+BEGIN_SRC emacs-lisp
  ;; HTML export の設定
  (require 'org-html)
  ;; default の style sheet は使わない
  (setq org-export-html-style-include-default nil)
  ;; -----------------------------------------------------------
  ;;; Website 用の org file の置き場所
  ;; @see http://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html
  (require 'org-publish)
  ;;
  ;; バックアップファイルを作成しない
  (setq make-backup-files nil)
  ;; cache の置き場所を ~/.emacs.d/tmp/org-timestamps/ に変える
  ;; (setq org-publish-timestamp-directory
  ;;       (convert-standard-filename (concat user-emacs-directory "tmp/org-timestamps/")))
  (setq org-publish-use-timestamps-flag nil)
  ;; project の設定
  (setq org-publish-project-alist
        '(
          ("emacs-setup"
           :base-directory "~/.emacs.d/site-start.d/"
           :exclude ".*\.el|^Makefile|.*\.gpg|sitemap\.org"
           :base-extension "org"
           :publishing-directory "~/Public/cc-env/Emacs/"
           :recursive nil
           :publish-function org-publish-org-to-html
           :auto-sitemap t
           :sitemap-filename "sitemap.org"
           :sitemap-title "sitemap"
           :headline-levels 2
           :auto-preamble t
           )
          ("web-org"
           :base-directory "~/Public/org/src/"
           :exclude "^menu.*\.org\\|cc-env\\|css\\|img\\|.*\.pdf\\|.*\.tex"
           :base-extension "org"
           :publishing-directory "~/Public/"
           :recursive t
           :publish-function org-publish-org-to-html
           :headline-levels 2
           :html-postamble auto  ;; default
           :auto-preamble t
           )
          ("web"
           :components ("web-org" "Emacs"))
          ))
  ;; ;;; insert skelton and export config files
  ;; ;;
  ;; ;; @see http://thenybble.de/projects/orgsite.html
  ;; ;;
  ;; (defvar my-website-base-dir "~/Public/org/src" "Base directory of Website")
  ;; (defvar my-website-config-name "export-config-")
  ;; (setq my-website-base-dir (expand-file-name "~/Public/org/src"))
  ;; (defun my-repeat-string (str times)
  ;;   (with-output-to-string
  ;;     (dotimes (i times)
  ;;       (princ str))))
  ;; (defun my-get-nesting-depth (filename basename)
  ;;   (with-temp-buffer
  ;;     (insert (file-relative-name filename basename))
  ;;     (goto-line 0)
  ;;     (count-matches "/")))
  ;; (defun my-make-website-conf-path (filename)
  ;;   (let ((nesting-level (my-get-nesting-depth filename my-website-base-dir)))
  ;;     (concat (my-repeat-string "../" (+ nesting-level 1))
  ;;             my-website-config-name (int-to-string nesting-level) ".org")))
  ;; (define-skeleton my-org-website-skeleton "" "Enter Title: "
  ;;   "#+TITLE: " str ?\n
  ;;   "#+SETUPFILE: "
  ;;   (my-make-website-conf-path (buffer-file-name)) ?\n
  ;;   "#+INCLUDE: "
  ;;   (my-make-website-conf-path (buffer-file-name)) ?\n ?\n
  ;;   "* " _ )
  ;; (defun my-org-website-insert-skeleton-maybe ()
  ;;   (if (and (buffer-file-name)
  ;;            (not (file-remote-p (buffer-file-name)))
  ;;            (string-match (concat "^" my-website-base-dir)
  ;;                          (expand-file-name (buffer-file-name))))
  ;;       (my-org-website-skeleton)))
  ;; (add-hook 'find-file-hook 'auto-insert)
  ;; (setq auto-insert-query nil)
  ;; (setq auto-insert-alist
  ;;       '((org-mode . my-org-website-insert-skeleton-maybe)))
#+END_SRC

* LaTeX export の設定
** 日本語LaTeX用の設定
DebianのLaTeXはまだUTF-8を処理できないので, EUC-JPでexportする.
#+BEGIN_SRC emacs-lisp
  ;; LaTeX export
  (require 'org-latex)
  (setq org-export-latex-coding-system 'euc-jp-unix)
  (setq org-export-latex-date-format "%Y年%m月%d日")
#+END_SRC
** jsarticle classの追加
   inputenc 等は読み込まないことにしてファイル毎にスタイルを設定する.
#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-export-latex-classes
               '("jsarticle"
                 "\\documentclass{jsarticle}
[NO-DEFAULT-PACKAGES]
[NO-PACKAGES]
[EXTRA]
"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
  (setq org-export-latex-default-class "jsarticle")
#+END_SRC
** latexmk
   PDF作成にはlatexmkを使う
#+BEGIN_SRC emacs-lisp
  (setq org-latex-to-pdf-process
        '("latexmk -pdfdvi %f"))
#+END_SRC
* Beamer export の設定
#+BEGIN_SRC emacs-lisp
  ;; LaTeX-Beamer export
  (require 'org-beamer)
  ;; デフォルトのヘッドラインレベル -> 2
  (setq org-beamer-frame-level 2)
  ;; frame のオプション
  (setq org-beamer-frame-default-options "[fragile]")
  (setq org-export-with-sub-superscripts nil)
#+END_SRC
* BibTeX連携
#+BEGIN_SRC emacs-lisp
  (my:not-locate-library org-exp-bibtex "site-lisp/org-mode/contrib/lisp")
  (require 'org-exp-bibtex)
  (defun org-mode-reftex-setup ()
    (load-library "reftex")
    (and (buffer-file-name)
         (file-exists-p (buffer-file-name))
         (reftex-parse-all))
    (define-key org-mode-map (kbd "C-c [") 'reftex-citation))
  (add-hook 'org-mode-hook 'org-mode-reftex-setup)
#+END_SRC
* Org-Babel
  ここで設定するより, 言語毎に設定した方が良い気がしてきた.
*** org-babel で使う言語の設定
#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(
     (ruby       . t)
     (sh         . t)
     (emacs-lisp . t)
     (ditaa      . t)
     (dot        . t)
     (R          . t)
     (gnuplot    . t)
     ))
#+END_SRC
*** org-babel のオプション
    block の評価時に問い合わせない
#+BEGIN_SRC emacs-lisp
  (setq org-confirm-babel-evaluate nil)
#+END_SRC
* export-generic の設定
** RD への export [0/1]
   - [ ] うまくいっていない. 行頭の空白をどうやって消すか
#+BEGIN_SRC emacs-lisp
  (my:not-locate-library org-export-generic "site-lisp/org-mode/contrib/lisp")
  (require 'org-export-generic)
  (org-set-generic-type
   "RD"
   '(
     :file-suffix ".rd"
                  :key-binding ?R
                  :title-format "%s\n"
                  :title-suffix ?=
                  :body-header-section-numbers nil
                  :body-header-section-number-format "%s) "
                  :body-section-header-prefix  ("\n= " "\n== " "\n=== " "\n==== " "\n+ ")
                  :body-section-header-format  "%s"
                  :body-section-header-suffix "\n"
                  :todo-keywords-export t
                  :body-line-format "%s\n"
                  :body-tags-export    t
                  :body-tags-prefix    " <tags>"
                  :body-tags-suffix    "</tags>\n"
                  :body-section-prefix   ""
                  :body-section-suffix   ""
                  :body-line-export-preformated t
                  :body-line-fixed-prefix  "\n"
                  :body-line-fixed-suffix  "\n"
                  :body-line-fixed-format  "%s\n"
                  :body-list-prefix    "\n"
                  :body-list-suffix    "\n"
                  :body-list-format    "* %s\n"
                  :body-number-list-prefix   "\n"
                  :body-number-list-suffix   "\n"
                  :body-number-list-format   "(1) %s\n"
                  :body-number-list-leave-number nil
                  :body-list-checkbox-todo "[_] "
                  :body-list-checkbox-todo-end ""
                  :body-list-checkbox-done "[X] "
                  :body-list-checkbox-done-end ""
                  :body-line-format  "%s"
                  :body-line-wrap  78
                  :body-text-prefix    ""
                  :body-text-suffix    ""
                  ))
#+END_SRC
* org2blog      :noexports:
  tDiaryもorgで書くようになってしまった.
** 導入
   org2blog と xml-rpc が必要.
   前者は github を submodule として登録しておく.
   後者は emacswiki から.
#+begin_example
  (auto-install-from-url "http://www.emacswiki.org/emacs/download/xml-rpc.el")
#+end_example
** 設定
#+BEGIN_SRC emacs-lisp
  ;; (when (string-match "daphne" system-name)
  ;;   (my:not-locate-library org2blog "site-lisp/org2blog")
  ;;   (require 'org2blog-autoloads)
  ;;   (require 'netrc)
  ;;   (setq blog (netrc-machine (netrc-parse "~/.xmlrpc.gpg") "uwabami.junkhub.org" t))
  ;;   (setq org2blog/wp-blog-alist
  ;;         '(("log"
  ;;            :url "http://uwabami.junkhub.org/log/xmlrpc.rb"
  ;;            :username (netrc-get blog "login")
  ;;            :password (netrc-get blog "password")
  ;;            :default-categories ("Emacs")
  ;;            :default-title "")))
  ;;   (setq org2blog/wp-use-tags-as-categories t)
  ;; )
#+END_SRC
