# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
# init-wl.org
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2011/12/19 10:32:22$
#
# Author: Youhei SASAKI <uwabami@gfd-dennou.org>
# License: Expat
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#+SETUPFILE: ~/.emacs.d/template/org/level-2.org
#+INCLUDE: ~/.emacs.d/template/org/menu-level-2.org
#+TITLE: 06. Wanderlust の設定

* 読み込み
#+BEGIN_SRC emacs-lisp
  (my:not-locate-library std11 "site-lisp/flim")
  (my:not-locate-library mime-setup "site-lisp/semi")
  (my:not-locate-library w3m-ems "site-lisp/w3m")
  (my:not-locate-library mmimap "site-lisp/wl/elmo")
  (my:not-locate-library wl "site-lisp/wl/lisp")
#+END_SRC
* TODO HTML メールの表示設定[0/1]
   HTMLメールの表示には w3m を使う.
   - [ ] w3m-el で外部リンクを踏む際に safe にする設定が良くわからない...Orz
#+BEGIN_SRC emacs-lisp
  (setq mime-setup-enable-inline-html t)
  (require 'mime-setup)
  (require 'w3m-ems)
  (require 'w3m-load)
  (require 'mime-w3m)
#+END_SRC
* デフォルトのメーラを Wanderlust に変更する
#+BEGIN_SRC emacs-lisp
  (autoload 'wl "wl" "Wanderlust" t)
  (autoload 'wl-other-frame "wl" "Wanderlust on new frame" t)
  (autoload 'wl-draft "wl-draft" "Write draft with Wanderlust." t)
  (if (boundp 'mail-user-agent)
      (setq mail-user-agent 'wl-user-agent))
  (if (boundp 'read-mail-command)
    (setq read-mail-command 'wl))
  (if (fboundp 'define-mail-user-agent)
    (define-mail-user-agent
      'wl-user-agent
      'wl-user-agent-compose
      'wl-draft-send
      'wl-draft-kill
      'mail-send-hook))
#+END_SRC
* キーバインド. F3 で Wanderlust を起動
#+BEGIN_SRC emacs-lisp
  (global-set-key [f3] 'wl)
#+END_SRC
* Wanderlust 本体の設定は基本外部ファイルで
   epa を有効にして gpg で暗号化したファイルを読む
#+BEGIN_SRC emacs-lisp
  (setq wl-init-file "~/.wl/init.gpg")
#+END_SRC
