# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
# 30lookup-el.org
#+begin_quote
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2011/11/28 13:15:12$
#
# Author: Youhei SASAKI <uwabami@gfd-dennou.org>
# License: GPL-3+
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#+end_quote
#+SETUPFILE: ~/.emacs.d/template/org/level-2.org
#+INCLUDE: ~/.emacs.d/template/org/menu-level-2.org
#+TITLE: lookup-elの設定
#Code:

** 読み込み
#+begin_src emacs-lisp
  (eval-when-compile (require 'lookup))
  (autoload 'lookup "lookup" nil t)
  (autoload 'lookup-region "lookup" nil t)
  (autoload 'lookup-pattern "lookup" nil t)
#+end_src
** キーバインドの設定
#+begin_src emacs-lisp
  (global-set-key "\C-cw" 'lookup-pattern)
  (global-set-key "\C-cW" 'lookup-word)
#+end_src
** 検索エージェント, 辞書の設定
#+begin_src emacs-lisp
  (setq lookup-search-agents
       '(
         (ndeb "/usr/local/share/dict/eijiro" :alias "英辞郎")
         (ndeb "/usr/local/share/dict/waeijiro" :alias "和英辞郎")
         (ndeb "/usr/local/share/dict/rikagaku5" :alias "理化学辞典")
         (ndeb "/usr/local/share/dict/koujien4" :alias "広辞苑")
         (ndeb "/usr/local/share/dict/wadai5" :alias "研究社 和英大辞典")
         ;; (ndeb "/usr/local/share/dict/shizenenja" :alias "自然科学系(英和)")
         ;; (ndeb "/usr/local/share/dict/shizenjaen" :alias "自然科学系(和英)")
         ;; (ndeb "/usr/local/share/dict/colloc" :alias "研究社 英和活用大辞典")
         ;; (ndeb "/usr/local/share/dict/eidai6" :alias "研究社 英和大辞典")
         ;; (ndest "~/Mail/.caskets" :alias "メール全文検索")
         ))
#+end_src
