# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
# init-auto-complete.org
#+begin_quote
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2011/11/28 16:07:12$
#
# Author: Youhei SASAKI <uwabami@gfd-dennou.org>
# License: Expat
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#+end_quote
#+SETUPFILE: ~/.emacs.d/template/org/level-2.org
#+INCLUDE: ~/.emacs.d/template/org/menu-level-2.org
#+TITLE: auto-complete の設定

** auto-complete の設定
- load-path の設定: パッケージがある場合はそれを読む
#+begin_src emacs-lisp
  (when (not (locate-library "auto-complete"))
    (add-to-load-path "site-lisp/auto-complete-el")
    (eval-when-compile
      (add-to-load-path "site-lisp/auto-complete-el")))
  (require 'auto-complete)
  ;; (ac-config-default)
  ;; デフォルトの補完候補
  ;(set-default 'ac-sources '(ac-source-abbrev ac-source-words-in-same-mode-buffers ac-source-yasnippet))
  ;; 対象の全てで補完を有効にする
  (global-auto-complete-mode t)
  ;; 自動で起動するのを停止
  (setq ac-auto-start nil)
  ;; 起動キーの設定
  ;;(ac-set-trigger-key "TAB")
  (define-key ac-mode-map (kbd "M-TAB") 'auto-complete)
  ;; 補完メニュー表示時のみ C-n/C-p で補完候補を選択
  (setq ac-use-menu-map t)
  (define-key ac-menu-map "\C-n" 'ac-next)
  (define-key ac-menu-map "\C-p" 'ac-previous)
  (define-key ac-completing-map (kbd "C-m") 'ac-complete)
  (define-key ac-completing-map (kbd "M-/") 'ac-stop)
  ;; 待ち時間を長めに取る
  (setq ac-delay 0.2)
  ;; 候補の最大件数 デフォルトは 10件
  (setq ac-candidate-limit nil)
  ;; 補完候補のソート
  (setq ac-use-comphist t)
  ;; クイックヘルプが表示されるとバッファが大きく変更される場合があるので停止
  (setq ac-use-quick-help nil)
  ;; 補完推測
  (setq ac-use-comphist nil)
  ;; flyspell-mode 用の対策
  (ac-flyspell-workaround)
#+end_src
