# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
# init-auto-complete.org
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2011/12/16 19:21:32$
#
# Author: Youhei SASAKI <uwabami@gfd-dennou.org>
# License: Expat
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#+SETUPFILE: ~/.emacs.d/template/org/level-2.org
#+INCLUDE: ~/.emacs.d/template/org/menu-level-2.org
#+TITLE: auto-complete の設定

* 読み込み
   Debian パッケージがある場合はそれを読む
#+begin_src emacs-lisp
  (my:not-locate-library auto-complete "site-lisp/auto-complete-el")
  (require 'auto-complete)
#+end_src
* 初期設定
** 全てのモードで補完を有効に
#+begin_src emacs-lisp
  (global-auto-complete-mode t)
#+end_src
** 自動起動の停止
#+begin_src emacs-lisp
  (setq ac-auto-start nil)
#+end_src
** キー設定
    M-Tab に割り当て
#+begin_src emacs-lisp
  (define-key ac-mode-map (kbd "M-TAB") 'auto-complete)
#+end_src
    補完メニュー表示時には C-n/C-p で選択
#+begin_src emacs-lisp
  (setq ac-use-menu-map t)
  (define-key ac-menu-map "\C-n" 'ac-next)
  (define-key ac-menu-map "\C-p" 'ac-previous)
  (define-key ac-completing-map (kbd "C-m") 'ac-complete)
  (define-key ac-completing-map (kbd "M-/") 'ac-stop)
#+end_src
** 表示関連
    待ち時間を長めに
#+begin_src emacs-lisp
  (setq ac-delay 0.2)
#+end_src
    補完候補をソート
#+begin_src emacs-lisp
  (setq ac-use-comphist t)
#+end_src
    補完候補の表示件数を無制限に(デフォルト10件)
#+begin_src emacs-lisp
  (setq ac-candidate-limit nil)
#+end_src
    クイックヘルプが表示されるとバッファが大きく変更される場合がるので停止
#+begin_src emacs-lisp
  (setq ac-use-quick-help nil)
#+end_src
    補完推測
#+begin_src emacs-lisp
  (setq ac-use-comphist nil)
#+end_src
** ヒストリ置き場の変更
#+begin_src emacs-lisp
  (setq ac-comphist-file (concat user-emacs-directory "tmp/ac-comphist.dat"))
#+end_src
* flyspell-mode 用の work around
#+begin_src emacs-lisp
  (ac-flyspell-workaround)
#+end_src
