(source gnu)
(source melpa)
(source org)

(depends-on "auctex-latexmk")
(depends-on "auto-complete")
(depends-on "bind-key")
(depends-on "c-eldoc")
(depends-on "cask")
(depends-on "cp5022x")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "eaw_and_emoji" :git "https://github.com/uwabami/locale-eaw-emoji" :files ("*.el"))
(depends-on "elmine")
(depends-on "elscreen" :git "https://github.com/knu/elscreen")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flx")
(depends-on "flx-ido")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "id-manager")
(depends-on "idle-highlight-mode")
(depends-on "ido-grid" :git "https://github.com/larkery/ido-grid.el")
(depends-on "japanese-holidays")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "org-agenda-property")
(depends-on "org-gcal")
(depends-on "org-journal")
(depends-on "orgmine" :git "https://github.com/kametoku/orgmine")
(depends-on "package-utils")
(depends-on "pallet")
(depends-on "password-store")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "rainbow-mode")
(depends-on "rspec-mode")
(depends-on "ruby-electric")
(depends-on "s")
(depends-on "scss-mode")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "systemd")
(depends-on "textile-mode")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "xclip")
(depends-on "yasnippet")
(depends-on "zotelo")
