(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "cp5022x")
(depends-on "darkpastel-theme")
(depends-on "elscreen")
(depends-on "exec-path-from-shell")
(depends-on "git-commit-mode")
(depends-on "id-manager")
(depends-on "magit")
(depends-on "offlineimap")
(depends-on "pallet")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yaml-mode")
;;;pallet-ignore
(depends-on "cp5022x" :git "https://github.com/awasira/cp5022x.el")
(depends-on "elscreen" :git "https://github.com/knu/elscreen")
(depends-on "darkpastel-theme" :git "https://github.com/uwabami/darkpastel-theme")
(depends-on "id-manager" :git "https://github.com/kiwanami/emacs-id-manager")