# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#+TITLE: AUCTeX の設定
#+AUTHOR: Youhei SASAKI
#+EMAIL: uwabami@gfd-dennou.org
#+DATE: 2015-04-22 23:03:15
#+LANG: ja
#+LAYOUT: page
#+CATEGORIES: cc-env emacs
#+PERMALINK: cc-env/emacs/config/auctex_config.html
* 始めに
  TeX 編集用のモードとしては YaTeX と AUCTeX がありますが,
  YaTeX の font-lock が遅いことから AUCTeX を使うように.

  以下の設定は「Latexmk を使ってタイプセットする」ことを前提にしています
  =XeLaTeX= や =LuaTeX= の処理は想定していないので,
  そういう場合には [[http://oku.edu.mie-u.ac.jp/~okumura/texwiki/?AUCTeX][TeXWiki の AUCTeX のページ]] なんかを参照のこと．
* 読み込み
  Debian パッケージの場合, =/etc/emacs/site-start.d/50auctex.el= において
  既に =auctex.el= と =preview-latex.el= が load されているため
  特に読み込みの設定は必要無い.
  Debian 以外の場合に, =auctex.el= と =preview-latex= を読み込む.
  #+BEGIN_SRC emacs-lisp
    (unless (file-exists-p "/etc/emacs/site-start.d/50auctex.el")
      (load "auctex.el" nil t)
      (load "preview-latex" nil t))
  #+END_SRC
* [[https://github.com/tom-tan/auctex-latexmk][auctex-latexmk]]
  AUCTeX で [[http://users.phys.psu.edu/~collins/software/latexmk-jcc/][Latexmk]] を使い,
  かつ platex 実行時に文字コード指定も追加してくれる.

  ここでは,
  - default の "LaTeX" を上書き
  - =dvips + ps2pdfwr= での処理の追加
  をしている.
  #+BEGIN_SRC emacs-lisp
    (defun my:auctex-latexmk-setup ()
      "Add LatexMk command to TeX-command-list."
      (delq (assoc "LaTeX" TeX-command-list) TeX-command-list)
      (add-to-list 'TeX-command-list
                   '("LaTeX" "latexmk -gg -pdfdvi %t" TeX-run-latexmk nil
                     (plain-tex-mode latex-mode doctex-mode) :help "Run LatexMk, with epLaTeX, dvipdfmx"))
      (add-to-list 'TeX-command-list
                   '("LaTeXMk" "latexmk %t" TeX-run-latexmk nil
                     (plain-tex-mode latex-mode doctex-mode) :help "Run LatexMk without any options"))
      (add-to-list 'TeX-command-list
                   '("LaTeXMk(ps2pdfwr)" "latexmk -gg -pdfps %t" TeX-run-latexmk nil
                     (plain-tex-mode latex-mode doctex-mode) :help "Run LatexMk, with (e)pLaTeX, dvips, ps2pdfwr"))
      (setq LaTeX-clean-intermediate-suffixes
            (append
             '("\\.fdb_latexmk" "\\.aux.bak" "\\.synctex.gz") LaTeX-clean-intermediate-suffixes))
      (setq TeX-command-output-list
            '(("latexmk" ("pdf")))))
    (add-hook 'LaTeX-mode-hook
              (function (lambda ()
                          (require 'auctex-latexmk nil 'noerror)
                          (my:auctex-latexmk-setup)
                          (add-to-list 'auctex-latexmk-encoding-alist
                                       '(iso-2022-jp      . "jis"))
                          (add-to-list 'auctex-latexmk-encoding-alist
                                       '(iso-2022-jp-unix      . "jis"))
                          )))
  #+END_SRC
  =~/.latexmkrc= の設定は以下の通り
  #+BEGIN_SRC perl
    #!/usr/bin/env perl
    $kanji  = "-kanji=$ENV{\"LATEXENC\"}" if defined $ENV{"LATEXENC"};
    $latex  = "platex -interaction=nonstopmode -src-specials -shell-escape --synctex=1 $kanji";
    $latex_silent = "platex -interaction=batchmode -src-specials -shell-escape --synctex=1 $kanji";
    $bibtex = "pbibtex $kanji";
    # disable makeindex/mendex
    $makeindex = "touch -m %D";
    # if ( $ENV{"LATEXENC"} == "jis" ){
    #     $makeindex = "mendex -J %O -c -r -o %D %S ";
    # } elsif ( $ENV{"LATEXENC"} == "euc" ){
    #     $makeindex = "mendex -E %O -c -r -o %D %S ";
    # } elsif ( $ENV{"LATEXENC"} == "sjis" ){
    #     $makeindex = "mendex -S %O -c -r -o %D %S";
    # } else {
    #     $makeindex = "mendex -U %O -c -r -o %D %S";
    # }
    $dvipdf = "dvipdfmx %O -o %D %S";
    $dvips = 'dvips %O -z -f %S | convbkmk -u > %D';
    $ps2pdf = 'ps2pdfwr %O %S %D';
    $pdf_mode = 3;
  #+END_SRC
* 日本語用の設定
** japanese-latex-mode 用の細工
   =japanese-latex-mode= において, 幾つかのコマンドが追加/上書きされている.
   あまり使うことの無いコマンドが表示されるのが嫌なので,
   それらを削除したり.
   #+BEGIN_SRC emacs-lisp
     (eval-after-load "tex-jp"
       '(progn
          ;; (setq japanese-LaTeX-default-style "jsarticle")
          (dolist (command '("pTeX" "pLaTeX" "pBibTeX" "jTeX" "jLaTeX" "jBibTeX"))
            (delq (assoc command TeX-command-list) TeX-command-list))
          ))
   #+END_SRC
** TeX-engine の設定
   どのタイミングで使われているのか良くわかっていないのだけれど, 一応設定しておく.
   #+BEGIN_SRC emacs-lisp
     (setq TeX-engine-alist
           '((ptex "pTeX"
                   "ptex %(kanji)%`%S%(PDFout)%(mode)% -shell-escape"
                   "platex %(kanji)%`%S%(PDFout)%(mode)% -shell-escape"
                   "eptex")
             (uptex "upTeX"
                    "uptex %(kanji)%`%S%(PDFout)%(mode)% -shell-escape"
                    "uplatex %(kanji)%`%S%(PDFout)%(mode)% -shell-escape"
                    "uptex")
             (pdfptex "PDFpLaTeX"
                      "ptex2pdf -e -ot ' %(kanji) %S -shell-escape %(mode)'"
                      "ptex2pdf -e -l -ot '%(kanji) %S -shell-escape %(mode)'"
                      "eptex")
             (pdfuptex "PDFupLaTeX"
                      "ptex2pdf -e -u -ot '%(kanji) %S -shell-escape %(mode)'"
                      "ptex2pdf -u -l -ot '%(kanji) %S -shell-escape %(mode)'"
                      "euptex")
             ))
     (setq TeX-engine 'pdfptex)
   #+END_SRC
   ちなみに
   =japanese-latex-mode= では
   =TeX-engine-alist-builtin= に =ptex, jtex, uptex= が追加(=setq=) されているため
   上記設定は不要(かも).
