# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#
# Copyright(C) Youhei SASAKI <uwabami@gfd-dennou.org> All rights reserved.
# $Lastupdate: 2012/09/11 13:00:21$
# License: Expat
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#+AUTHOR: Youhei SASAKI
#+EMAIL:  uwabami@gfd-dennou.org
#+TITLE: calfw: カレンダーの設定
#+BEGIN_HTML
---
layout: emacs
title: calfw: カレンダーの設定
---
#+END_HTML
* 始めに

最近は予定の管理は google カレンダー一本です.
携帯で閲覧/追加できるのも良い感じです.
ですが Emacs からも予定の閲覧や管理がしたくなります. ここではその設定とか.

* 日本の休日の追加
  el-get 用のレシピも書いておきました.
#+BEGIN_SRC emacs-lisp
  (unless (locate-library "japanese-holiday")
    (el-get 'sync 'japanese-holiday))
  (add-hook 'calendar-load-hook
            (lambda ()
              (require 'japanese-holidays)
              (setq calendar-holidays
                    (append japanese-holidays holiday-local-holidays holiday-other-holidays))))
#+END_SRC
* calfw の導入と設定
  Debian にはパッケージがあります. 無い場合は el-get
#+BEGIN_SRC emacs-lisp
  (unless (locate-library "calfw")
    (el-get 'sync 'calfw))
#+END_SRC
* google calendar/howm との連携
  #+BEGIN_SRC emacs-lisp
    (eval-after-load "howm-menu"
      '(progn
         (require 'calfw-howm)
         (require 'calfw-ical)
         (cfw:install-howm-schedules)
         (define-key howm-mode-map (kbd "M-C") 'cfw:elscreen-open-howm-calendar)
         (setq cfw:howm-schedule-contents
               (list
                (cfw:ical-create-source "KUSM" "~/Mail/ics/KUSM.ics" "Green")
                (cfw:ical-create-source "My" "~/Mail/ics/MyCalendar.ics" "#ffff4c")
                (cfw:ical-create-source "GFD" "~/Mail/ics/GFD.ics" "#ff4c4c")
                (cfw:ical-create-source "DebianJP" "~/Mail/ics/DebianJP.ics" "#4cffff")
                ))
         ))
   #+END_SRC
