# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#
# Copyright(C) Youhei SASAKI <uwabami@gfd-dennou.org> All rights reserved.
# $Lastupdate: 2012/09/02 02:38:06$
# License: Expat
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#+AUTHOR: Youhei SASAKI
#+EMAIL:  uwabami@gfd-dennou.org
#+TITLE: flymake の設定
#+SETUPFILE: ./export-config.org
#+BEGIN_HTML
---
layout: emacs
title: flymakeの設定
---
#+END_HTML
* はじめに
  [[http://flymake.sourceforge.net/][flymake]] はリアルタイムに動作する文法チェッカです.
* 基本設定
  #+BEGIN_SRC emacs-lisp
    (require 'flymake)
    ;; disable GUI
    (setq flymake-gui-warnings-enabled nil)
    ;; enabled all file mode
    (add-hook 'find-file-hook 'flymake-find-file-hook)
  #+END_SRC
* Fortran
  コンパイラとして gfortran を想定しています.
  ただ, gfortran の -fsyntax-only 出力は gcc とはだいぶ異なるので
  以下の様な安直な wrapper を噛ませてチェックすることにしています
  #+BEGIN_SRC ruby
    #!/usr/bin/env ruby
    # -*- mode: ruby; coding: utf-8; indent-tabs-mode: nil -*-
    #
    # Copyright(C) Youhei SASAKI <uwabami@gfd-dennou.org> All rights reserved.
    # $Lastupdate: 2012/09/02 02:17:50$
    # License: Expat
    #
    # Permission is hereby granted, free of charge, to any person obtaining
    # a copy of this software and associated documentation files (the
    # "Software"), to deal in the Software without restriction, including
    # without limitation the rights to use, copy, modify, merge, publish,
    # distribute, sublicense, and/or sell copies of the Software, and to
    # permit persons to whom the Software is furnished to do so, subject to
    # the following conditions:
    #
    # The above copyright notice and this permission notice shall be
    # included in all copies or substantial portions of the Software.
    #
    # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    # EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    # MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    # NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
    # LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
    # OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
    # WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
    #
    # Code:
    @hold = nil
    @fname = nil
    @line = nil
    @ch = nil
    while input = ARGF.gets
      @input = input
      if @input =~ /^ / || @input =~/^\s*$/ || @input =~/^\s*1\s*$/
        @hold = @input
      elsif @input =~ /^(Warning|Error):/ && ( @fname && @line && @ch)
        puts "#{@fname}:#{@line}: #{@input.chomp} (ch.#{@ch})"
      elsif @input =~ /^(.+?):(\d+?)\.(\d+):(\s*)/
        @fname,@line,@ch = $1, $2, $3
        @hold = @input
      else
        @hold = @input
        puts @hold
        @hold = nil
        @fname = nil
        @line = nil
        @ch = nil
      end
    end

  #+END_SRC
