# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2012/08/08 15:41:35$
# License: Expat
#
#+TITLE: howm の設定
#+AUTHOR: Youhei SASAKI
#+EMAIL: uwabami@gfd-dennou.org
#+SETUPFILE: ./export-config.org
#+BEGIN_HTML
---
layout: emacs
title: howm の設定
---
#+END_HTML

* 始めに
  [[http://howm.sourceforge.jp/index-j.html][Howm]] [fn:1]は お手軽なメモ環境です. 本家によれば
  #+BEGIN_QUOTE
  Emacs で断片的なメモをどんどんとるための環境です. 分類機能はあえてつけません. かわりに, 全文検索とメモ間リンクが手軽にできるようにしました. 自由書式なので改宗も不要 :-)
  #+END_QUOTE
  ということです. 非常に便利で, 無いと途方に暮れてしまします.

  ちなみに私はメモの形式は Org にしています.
* load-path の確認と追加
  無いと途方に暮れるので, 環境に howm が無い場合には site-lisp/howm に install してある howm を load-path に追加.
  elscreen-howmも同様.
  #+BEGIN_SRC emacs-lisp
    (my:not-locate-library howm "site-lisp/howm")
    (my:not-locate-library elscreen-howm "site-lisp/elscreen")
  #+END_SRC
* ディレクトリの設定
  メモの内容は dropbox で同期することに
  #+BEGIN_SRC emacs-lisp
    (setq howm-directory "~/Documents/Dropbox/org")
    (setq howm-file-name-format "%Y%m%d-%H%M%S.howm")
    (setq howm-keyword-file "~/Documents/Dropbox/org/.howm-keys")
    (setq howm-history-file "~/Documents/Dropbox/org/.howm-history")
    (setq howm-menu-file "~/Documents/Dropbox/org/.howm-menu")
  #+END_SRC

* org-mode でメモを書くためにその1
  メモはorgで書くので, org-mode の hook として howm-mode を登録しておきます.
  こうすると C-c が org に取られるので, howm の prefix は C-xC-z にしておきます
  #+BEGIN_SRC emacs-lisp
    ;; 素の org の時も howm
    (add-hook 'org-mode-hook 'howm-mode)
    ;; .org は org + howm
    (add-to-list 'auto-mode-alist '("\\.org" . org-mode))
    ;; .howm も org + howm
    (add-to-list 'auto-mode-alist '("\\.howm$" . org-mode))
    ;; title header は "=" のままで
    (setq howm-view-title-header "=")
    ;; ちなみに org に揃える"*"こともできるけれど, 長い文章を書くときに
    ;; シンドイと思う
    ;; (setq howm-view-title-header "*")
   #+END_SRC
* 読み込み
  elscreen-howm で define-key (kbd "C-c C-c") されていることに注意.
  これは org と被る!!
  #+BEGIN_SRC emacs-lisp
    ;; \C-x\C-z を使う -> C-c は org-mode と被るから.
    (global-unset-key (kbd "C-x C-z"))
    (setq howm-prefix (kbd "C-x C-z"))
    (require 'howm)
    (require 'elscreen-howm)
  #+END_SRC
* org-mode でメモを書くためにその2
  #+BEGIN_SRC emacs-lisp
    (eval-after-load "howm-mode"
      '(progn
         ;; \C-c \C-c は org に渡す
         (define-key howm-mode-map (kbd "C-c C-c") nil)
         ;; メモ書いたら elscreen を kill -> 要 elscreen-howm
         (define-key howm-mode-map (kbd "C-x C-z C-c")
           'howm-save-and-kill-buffer/screen)))
    ;; \C-x m で howm-create -> clmemo 風
    (define-key ctl-x-map "m" 'howm-create)
    ;; skk と併用するための設定(Dired-X に C-xC-j を奪われないように)
    (setq dired-bind-jump nil)
  #+END_SRC
* 検索などの設定
  結構きまり文句かも.
  Linux以外の環境で GNU grep を使う際の条件分岐は
  ちょっと真面目に設定した方が良いかも. あるいは grep 使わない?
  #+BEGIN_SRC emacs-lisp
    ;; 検索で大文字小文字を区別しない
    (setq howm-keyword-case-fold-search t)
    ;; grep の設定
    ;; (setq howm-view-use-grep t)
    (setq howm-view-grep-command "egrep")
    (setq howm-view-fgrep-command "fgrep")
    (setq howm-view-grep-extended-option nil)
    (setq howm-view-grep-fixed-option nil)
    (setq howm-view-grep-file-stdin-option nil)
    ;; 全文検索の対象ディレクトリ<- 追加しない
    (setq howm-search-other-dir nil)
    ;; 検索対象除外ファイル
    ;; ad hoc にどんどん増えていくなぁ...
    (setq howm-excluded-file-regexp
          "/\\.#\\|[~#]$\\|\\.bak$\\|/CVS/\\|\\.doc\\|\\.pdf\\|\\.txt$\\|\\.html$\\|\\.tex$\\|\\.dvi$\\|\\.fdb_latexmk$\\|\\.ppt$\\|\\.xls$\\|\\.howm-menu$\\|.howm-keys$\\|\\.png$\\|\\.gif$\\|\\.tif$\\|\\.tiff$\\|\\.jpg$\\|\\.jpeg$")
  #+END_SRC
* メニューなどの表示の設定
  #+BEGIN_SRC emacs-lisp
  ;; 決まり文句?
  (setq howm-menu-top nil)
  (setq howm-menu-lang 'ja)
  ;; 一覧にタイトルを表示しない
  (setq howm-list-title nil)
  ;; save 時にメニューを更新しない
  (setq howm-menu-refresh-after-save nil)
  (setq howm-refresh-after-save nil)
  ;; 新規メモを上に
  (setq howm-prepend t)
  ;; 全メモ一覧時にタイトル表示
  (setq howm-list-all-title t)
  ;; 「最近のメモ」一覧時にタイトル表示
  (setq howm-list-recent-title t)
  ;; 「最近のメモ」の表示件数
  (setq howm-menu-recent-num 30)
  ;;  完了(.) は表示しない
  (setq howm-todo-menu-types "[-+~!]")
  ;; メニューを 2 時間キャッシュ
  (setq howm-menu-expiry-hours 2)
  ;; RET でファイルを開く際, 一覧バッファを消す. C-u RET なら残る
  (setq howm-view-summary-persistent nil)
  ;; 21 日前から3 日後まで
  (setq howm-menu-schedule-days-before 10)
  #+END_SRC
* 編集テンプレートの設定
  #+BEGIN_SRC emacs-lisp
  ;; howm のテンプレートのカスタマイズ
  (setq howm-template-date-format "[%Y-%m-%d %H:%M:%S]")
  (setq howm-template-file-format "==>%s")
  (setq howm-template "%date%file\n= %cursor\n\n")
  #+END_SRC
* [[http://howm.sourceforge.jp/cgi-bin/hiki/hiki.cgi?ExternalTool][併用ツール]] [fn:2]
  そのうちなにか書くかも.
* Footnotes
[fn:1] Howm: [[http://howm.sourceforge.jp/index-j.html]]

[fn:2] 併用ツール - Howm Wiki: [[http://howm.sourceforge.jp/cgi-bin/hiki/hiki.cgi?ExternalTool]]


