# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2012/03/29 19:03:24$
# License: GPL-3+
#
#+TITLE: Emacsの基本設定
#+AUTHOR: Youhei SASAKI
#+EMAIL: uwabami@gfd-dennou.org
* 始めに
  ~/.emacs→~/.emacs.d/init.el ときて, このファイルで
  基本設定と外部elispの読み込みを行っています.

  外部elispの設定は多くの場合別ファイルに分けていますが,
  設定が短い場合にはこのファイルに記述して終わっていたりします.
* 言語の設定
** 基本設定
   Emacs23以降はEmacs内部がUTF-8で記述されるようになったので, 極力
   UTF-8を使用するようにしています(EUC-JPとかで使用すると稀に祟りがあっ
   たりします).

   過去の資源(特にTeX)に関しては, 未だEUC-JPのファイルも多いので注意す
   る必要があります. Debian unstalbeにTeXLive2011が入ったので, そのうち
   全部UTF-8に移行しますが(とはいえ過去の資産や共同作業する原稿なんかは
   無理ですけれど...).
   #+BEGIN_SRC emacs-lisp
     (set-language-environment "Japanese")
     (prefer-coding-system 'utf-8)
     ;; (set-default-coding-systems 'utf-8)
     ;; (set-terminal-coding-system 'utf-8)
     ;; (set-keyboard-coding-system 'utf-8)
     ;; (set-buffer-file-coding-system 'utf-8)
   #+END_SRC
*** 補足: 言語設定の確認
    #+BEGIN_EXAMPLE
    (set-language-environment "Japanese")
    #+END_EXAMPLE
    によってlocaleが設定されます. "Japanese"という大雑把な設定で
    何が設定されるのかは
    #+BEGIN_EXAMPLE
    (describe-variable 'language-info-alist)
    #+END_EXAMPLE
    を実行して "Japanese"を参照すると良いです. 試しに実行してみると
    #+BEGIN_EXAMPLE
    ...
     ("Japanese"
      (documentation . t)
      (sample-text . "Japanese (日本語)	こんにちは, ｺﾝﾆﾁﾊ")
      (features japan-util)
      (input-method . "japanese")
      (coding-priority iso-2022-jp japanese-iso-8bit japanese-shift-jis iso-2022-jp-2004 euc-jis-2004 japanese-shift-jis-2004 iso-2022-jp-2)
      (coding-system iso-2022-jp japanese-iso-8bit japanese-shift-jis japanese-iso-7bit-1978-irv iso-2022-jp-2004 japanese-shift-jis-2004 euc-jis-2004)
      (charset japanese-jisx0208 japanese-jisx0212 latin-jisx0201 katakana-jisx0201 japanese-jisx0213\.2004-1 japanese-jisx0213-1 japanese-jisx0213-2 japanese-jisx0208-1978)
      (tutorial . "TUTORIAL.ja")
      (iso639-language . ja)
      (exit-function . use-default-char-width-table)
      (setup-function . setup-japanese-environment-internal))
    ...
    #+END_EXAMPLE
    となっていました. coding-priorityを見るとわかるように
    文字コードの自動判定などの大雑把な優先順位はiso-2022-jp→shift_jis→euc-jp...
    となっていて, どこにも utf-8 がありません.
    utf-8 を優先するには
    #+BEGIN_EXAMPLE
    (prefere-coding-system 'utf-8)
    #+END_EXAMPLE
    を設定します.
** OSの違いに起因する条件分岐
   全部Unix/Linux環境ならばこういう設定は不要なんでしょうけれど,
   幾つか環境を渡り歩いていると, こういった[[http://0xcc.net/misc/bad-knowhow.html][バッドノウハウ]] [fn:1]
   が増えていきます.

   MacとLinuxでは同じUnicodeでも正規化が異なります(具体的にはMacのファ
   イルシステムであるHFS+ではUnicodeの正規化が異なります). 日本語のファ
   イル名を扱うことは滅多にありませんが, たまに祟りがあるのでそれを回避
   するための設定をしておきます.

   Unicodeの正規化とMac OS X特有の事情については
    - [[http://homepage1.nifty.com/nomenclator/unicode/normalization.htm][Unicode正規化とは]]
    - [[http://www.sakito.com/2010/05/mac-os-x-normalization.html][Mac OS X におけるファイル名に関するメモ(NFC, NFD等)]]
   等が参考になるかと思います.

   Windows の場合はファイル名などは cp932 にしています. とはいえ最近
   Windows使っていないので良く知りません.
   #+BEGIN_SRC emacs-lisp
     (cond
      (darwin-p
       (require 'ucs-normarize)
       (setq file-name-coding-system 'utf-8-hfs)
       (setq locale-coding-system 'utf-8-hfs)
       ;; ついでにキーバインド
       (global-set-key (kbd "M-v") 'yank)
       ;; Cmd と Option を逆にする
       (setq ns-command-modifier 'meta)
       (setq ns-alternate-modifier 'super)
       (global-set-key [ns-drag-file] 'ns-find-file))
      (nt-p
       (setq file-name-coding-system 'cp932)
       (setq locale-coding-system 'cp932))
      (t
       (setq file-name-coding-system 'utf-8)
       (setq locale-coding-system 'utf-8))
     )
   #+END_SRC
*** 補足
    prefer-coding-systemを設定するとdefault-file-name-coding-systemが設
    定されます. これとfile-name-coding-systemの順位は
    #+BEGIN_QUOTE
    file-name-coding-systemがnil→default-file-name-coding-systemを利用
    #+END_QUOTE
    となっています.

    darwin-pとnt-pは~/.emacs.d/init.elで設定した環境判定用の変数です.
** cp5022xの利用
   Emacs23から内部がUnicodeベースになっています. しかし文字コードの変換
   はGNU libcのiconvをベースにしているため, 環境によっては文字の変換が
   うまく行なえません.
   cp5022xについては [[http://nijino.homelinux.net/emacs/emacs23-ja.html][Emacs23 日本語向け設定例]] [fn:2]を参照して下さい.
   また, [[http://d.hatena.ne.jp/kiwanami/about][kiwanami]] さんが [[http://d.hatena.ne.jp/kiwanami/20091103/1257243524][Wanderlustと文字コード]] [fn:3]というエントリで素
   晴しい解説を書いて下さっています.

   cp5022x 自体は auto-install.el で install しており,
   ~/.emacs.d/auto-install/ 以下に置いています. 本来は外部 elisp なので
   [[file:auto-install.org][auto-install の設定]] で設定するべきなんですが, 他にも影響がありそうなの
   でここで読み込んでいます.
*** install
    以下をauto-install-elで評価してinstallします.
    #+BEGIN_EXAMPLE
      (auto-install-from-url "http://nijino.homelinux.net/emacs/cp5022x.el")
    #+END_EXAMPLE
*** 読み込み
    単に読み込むだけです.
    #+BEGIN_SRC emacs-lisp
      (require 'cp5022x)
    #+END_SRC
* 機種依存しない(ハズ)の雑多な設定
  Emacsそのものの設定集.
  line-number-modeなど「有効無効をtoggleする関数」は,
  慣習的に0以下の数字を指定すると明示的に無効化できる.
** 常に $HOME から開始
   以前(Meadow?)で使っていた時に Cygwin のHOME に移動していないとファイル
   を開くのが大変だったので指定していた. これを指定していると
   byte-compile 時に CURDIR を設定する必要があったりして面倒だが,
   まだ残している.
   #+BEGIN_SRC emacs-lisp
     (cd "~/")
   #+END_SRC
** キーバインドの設定
   設定しておいて, 結構忘れていたり.
   とはいえ[home]と[end]は無いと途方に暮れます.
   鬼軍曹.el [fn:4] とかで強制した方が良いのかもしれません.
   #+BEGIN_SRC emacs-lisp
     (global-set-key (kbd "C-h")     'backward-delete-char)
     (global-set-key (kbd "C-c M-a") 'align-regexp)
     (global-set-key (kbd "C-c ;")   'comment-region)
     (global-set-key (kbd "C-c M-;") 'uncomment-region)
     (global-set-key (kbd "C-/")     'undo)
     (global-set-key (kbd "C-c M-r") 'replace-regexp)
     (global-set-key (kbd "C-c r")   'replace-string)
     (global-set-key (kbd "<home>")  'beginning-of-buffer)
     (global-set-key (kbd "<end>")   'end-of-buffer)
   #+END_SRC
** モードライン関連
*** モードラインのダイエット
    デフォルトでは結構煩いので, いろいろと消す. 元ネタは
    [[http://homepage1.nifty.com/blankspace/emacs/mode-line.html][mode-line-formatをダイエットさす]]モードラインのダイエット [fn:5]

    しかし世の中にはもっと過激な人もいらっしゃって
    [[http://emacs-fu.blogspot.jp/2011/08/customizing-mode-line.html][customizing the mode-line]] [fn:6]なんてこともできる.
    そのうちもっと細かく設定するかも.
    #+BEGIN_SRC emacs-lisp
      (setq-default mode-line-format
                    '("-"
                      mode-line-mule-info
                      mode-line-modified
                      " "
                      mode-line-buffer-identification
                      " "
                       global-mode-string
                       " %[("
                       mode-name
                       mode-line-process
                       minor-mode-alist
                       "%n" ")%]"
                       (which-func-mode ("" which-func-format "-"))
                      "-%-"
                      )
                    )
    #+END_SRC
*** 行番号, 桁番号
    必要に応じて linum-mode を有効にするので
    モードラインにカーソルのある行番号や桁番号を表示しない.
    #+BEGIN_SRC emacs-lisp
      (line-number-mode 0)
      (column-number-mode 0)
    #+END_SRC
*** linum-mode を有効にした場合の桁表示を 5 桁に.
    #+BEGIN_SRC emacs-lisp
      (setq linum-format "%5d ")
    #+END_SRC
** フレーム, ツールバーなど
*** ツールバーは使用しない.
    #+BEGIN_SRC emacs-lisp
      (tool-bar-mode 0)
    #+END_SRC
*** スクロールバーは使用しない.
    #+BEGIN_SRC emacs-lisp
      (set-scroll-bar-mode nil)
    #+END_SRC
*** メニューバーを表示しない.
    #+BEGIN_SRC emacs-lisp
      (menu-bar-mode 0)
    #+END_SRC
*** bell-mode 使用しない
    #+BEGIN_SRC emacs-lisp
      (setq ring-bell-function 'ignore)
    #+END_SRC
*** startup を表示しない
    #+BEGIN_SRC emacs-lisp
      (setq inhibit-startup-screen 0)
    #+END_SRC
*** 可能ならば \C-x f で画像を表示
    #+BEGIN_SRC emacs-lisp
      (when (window-system)
        (setq auto-image-file-mode t)
        (setq auto-image-file-mode nil))
    #+END_SRC
** 表示/編集関連
*** 余計な空行を入れない
    #+BEGIN_SRC emacs-lisp
      ;; バッファ終端で newline を入れない
      (setq next-line-add-newlines nil)
      ;; ;; 保存時に最終行に一行追加するとりあえず使わないことに
      ;; (setq require-final-newline t)
      (put 'set-goal-column 'disabled nil)
    #+END_SRC
*** yes or no を y or n に
    #+BEGIN_SRC emacs-lisp
      (fset 'yes-or-no-p 'y-or-n-p)
    #+END_SRC
*** 選択リージョンに色付け
    #+BEGIN_SRC emacs-lisp
      (setq transient-mark-mode t)
    #+END_SRC
*** 対応する括弧を色付け
    #+BEGIN_SRC emacs-lisp
      (setq show-paren-delay 0)           ; 初期値は 0.125
      (setq show-paren-style 'expression) ; 括弧内も強調表示
      (show-paren-mode t)                 ; 有効化
    #+END_SRC
*** タイトルのバッファ名を非表示
    #+BEGIN_SRC emacs-lisp
      (setq frame-title-format nil)
    #+END_SRC
*** tab 幅 4, tab でのインデントはしない
    #+BEGIN_SRC emacs-lisp
      (setq-default tab-width 4)
      (setq-default indent-tabs-mode nil)
    #+END_SRC
*** 文字列は 72 文字で折り返し(RFC2822)
    #+BEGIN_SRC emacs-lisp
      (setq-default fill-column 72)
      (setq paragraph-start '"^\\([ 　・○<\t\n\f]\\|(?[0-9a-zA-Z]+)\\)")
      (setq-default auto-fill-mode nil)
    #+END_SRC
*** 行末の無駄な空白を削除する
    元ネタ: (Emacs Advent Calendar jp:2010)[fn:7]

    モード毎に設定した方が無難かもしれない.
    #+BEGIN_SRC emacs-lisp
      (add-hook 'before-save-hook 'delete-trailing-whitespace)
    #+END_SRC
*** バックアップとauto-saveの作成
    my:emacs-backup-dir を設定して, ~/.emacs.d/tmp/ 以下に
    backup と auto-save ファイルを集約することに.
    #+BEGIN_SRC emacs-lisp
      (setq auto-save-list-file-prefix
            (concat my:user-emacs-temporary-directory ".saves-"))
      (setq auto-save-default t)
      (setq auto-save-timeout 15)
      (setq auto-save-interval 60)
      (setq make-backup-files t)
      (setq backup-directory-alist
            `(("." . ,my:user-emacs-temporary-directory)))
      (setq auto-save-file-name-transforms
            `((".*" ,my:user-emacs-temporary-directory t)))
      (setq version-control t)
      (setq kept-new-versions 5)
      (setq kept-old-versions 5)
      (setq delete-old-versions t)
      (setq delete-auto-save-files t)
    #+END_SRC
*** 空になったファイルを尋ねずに自動削除
    #+BEGIN_SRC emacs-lisp
      (if (not (memq 'delete-file-if-no-contents after-save-hook))
          (setq after-save-hook
                (cons 'delete-file-if-no-contents after-save-hook)))
      (defun delete-file-if-no-contents ()
        (when (and
               (buffer-file-name (current-buffer))
               (= (point-min) (point-max)))
          (delete-file
           (buffer-file-name (current-buffer)))))
    #+END_SRC
*** scratch を殺さない. 消したら再生成
    #+BEGIN_SRC emacs-lisp
      (defun my:make-scratch (&optional arg)
        (interactive)
        (progn
          ;; "*scratch*" を作成して buffer-list に放り込む
          (set-buffer (get-buffer-create "*scratch*"))
          (funcall initial-major-mode)
          (erase-buffer)
          (when (and initial-scratch-message (not inhibit-startup-message))
            (insert initial-scratch-message))
          (or arg
              (progn
                (setq arg 0)
                (switch-to-buffer "*scratch*")))
          (cond ((= arg 0) (message "*scratch* is cleared up."))
                ((= arg 1) (message "another *scratch* is created")))))
      (defun my:buffer-name-list ()
        (mapcar (function buffer-name) (buffer-list)))
      (add-hook 'kill-buffer-query-functions
                ;; *scratch* バッファで kill-buffer したら内容を消去するだけにする
                (function (lambda ()
                            (if (string= "*scratch*" (buffer-name))
                                (progn (my:make-scratch 0) nil)
                              t))))
      (add-hook 'after-save-hook
                ;; *scratch* バッファの内容を保存したら
                ;; *scratch* バッファを新しく作る.
                (function
                 (lambda ()
                   (unless (member "*scratch*" (my:buffer-name-list))
                     (my:make-scratch 1)))))

    #+END_SRC
*** モードラインのファイル名にディレクトリも表示
    #+BEGIN_SRC emacs-lisp
      (require 'uniquify)
      (setq uniquify-buffer-name-style 'post-forward-angle-brackets)
      (setq uniquify-min-dir-content 1)
    #+END_SRC
*** saveplace で前回の修正位置を記憶
    記憶の保存先は ~/.emacs.d/tmp/emacs-places に
    #+BEGIN_SRC emacs-lisp
      (require 'saveplace)
      (setq-default save-place t)
      (setq save-place-file
            (convert-standard-filename
             (concat user-emacs-directory "tmp/emacs-places")))
    #+END_SRC

** emacs-server
   既に emacs-server が起動しているならば何もせず,
   起動していない場合には emacs-server を起動する.
   #+BEGIN_SRC emacs-lisp
     (eval-and-compile (require 'server))
     (when (and (functionp 'server-running-p)
                (not (server-running-p)))
       (server-start))
   #+END_SRC
** browse-url
   firefox → emacs-w3m → w3 の順で探索
   #+BEGIN_SRC emacs-lisp
     (require 'browse-url)
     (cond
      ((executable-find "firefox")
       (setq browse-url-browser-function 'browse-url-firefox))
      ((and (executable-find "w3m")
            (locate-library "w3m"))
       (setq browse-url-browser-function 'w3m-browse-url))
      (t
       (setq browse-url-browser-function 'browse-url-w3)))
     (global-set-key (kbd "C-c C-j") 'browse-url-at-point)
   #+END_SRC
** timestamp の自動更新
   ファイル内に"＄Lastupdate: ＄" (＄は小文字)がある場合には,
   save する度にtimestamp を更新する.
   #+BEGIN_SRC emacs-lisp
     (require 'time-stamp)
     (add-hook 'before-save-hook 'time-stamp)
     (setq time-stamp-active t)
     (setq time-stamp-line-limit 10)
     (setq time-stamp-start "$Lastupdate: ")
     (setq time-stamp-format "%04y/%02m/%02d %02H:%02M:%02S")
     (setq time-stamp-end "\\$")
   #+END_SRC
** TODO EasyPG[0/1]
   Emacs23からは本体に同梱されているのでrequireする必要ないが,
   一応残しておく
   - [ ] gpg-agentと対称鍵暗号化方式の共存が変
     - Mewみたいに独自にgpg-agent実装しているのもあって良くわからない
   #+BEGIN_SRC emacs-lisp
     (require 'epa-file) ; 読み込み
     ;; 対称鍵のキャッシュを有効化
     (setq epa-file-cache-passphrase-for-symmetric-encryption t)
   #+END_SRC
* 分割した設定ファイルの読み込み/外部emacs-lispなどの設定
  以下は Emacs 本体に同梱されていない emacs-lisp program や
  外部ファイルの設定を読み込んでいるモン, など.
** [[http://www.kanji.zinbun.kyoto-u.ac.jp/~tomo/elisp/APEL/][APEL]] [fn:8] に load-path を通しておく
   Upstream の Web には
   #+BEGIN_QUOTE
   APEL (A Portable Emacs Library) は可搬性のある Emacs Lisp program の作成を支援するための library です。
   #+END_QUOTE
   とある.
   今ん所, 使っている外部emacs-lispでは
   Wanderlustとhowmがapelに依存している.
   後者は無いと途方に暮れてしまうので,
   ここでload-pathの設定をしておく.
   #+BEGIN_SRC emacs-lisp
   (my:not-locate-library emu "site-lisp/apel")
   #+END_SRC
** [[http://www.morishima.net/~naoto/elscreen-en/][ElScreen]]
   Emacsのバッファを GNU Screen っぽく扱う.
   設定はキーバインドを \C-o に変えたくらい.
   #+BEGIN_SRC emacs-lisp
     (my:not-locate-library elscreen "site-lisp/elscreen")
     (setq elscreen-prefix-key (kbd "C-o"))
     (if (eq window-system 'x)
         (setq elscreen-display-tab 4)
       (setq elscreen-display-tab nil)
       )
     (setq elscreen-tab-display-kill-screen nil)
     (require 'elscreen)
     ;; (my:not-locate-library elscreen-dired-enhance "local-lisp")
   #+END_SRC
** 日本語入力
   SKK をメインで使用中. 無いと途方に暮れる.
   一応debug用にmozcも読み込んでいるが, 殆ど使った事がない.

   ちなみにGTKが有効になっているとgit-immoduleなんかと衝突するので
   .Xresources で xim を無効にしておくと良い.
   #+BEGIN_EXAMPLE
     ! disable XIM
     Emacs*useXIM: false
   #+END_EXAMPLE
   なんて ~/.Xresources に書いておく.

   ddskk 以前の古い skk が導入されている場合には
   site-lisp 以下の ddskk を load する.

   skk-user-directory を設定しているので辞書や id なんかは
   ~/.emacs.d/etc/skk 以下に置かれるが, 設定ファイルだけは
   [[file:ddskk.org][DDSKKの設定]] で行なっている.
    #+BEGIN_SRC emacs-lisp
      ;; mozc はとりあえず読み込んだだけ
      (require 'mozc nil t)
      ;;; skk の設定
      ;; 古い skk しか無い場合には ddskk を読み込む
      (my:not-locate-library skk-sticky "site-lisp/ddskk")
      ;; byte-compile 用の設定
      (eval-when-compile
        (require 'skk-vars)
        (require 'skk-autoloads))
      ;; ddskk の辞書ファイル等は ~/.emacs.d/etc/skk 以下に置く
      (setq skk-user-directory
            (concat my:user-emacs-etc-directory "skk"))
      ;; ただし設定ファイルだけは ~/.emacs.d/config 以下に置く
      (setq skk-init-file
            (concat my:user-emacs-config-directory "ddskk_config"))
      ;; org-babel-tangle で ddskk.org から ddskk.el を生成
      (my:org-babel-tangle-and-compile-file
       (concat my:user-emacs-config-directory "ddskk_config.org"))
      ;; ddsk の設定ファイルは自動で byte-compile
      (setq skk-byte-compile-init-file t)
      ;; 読み込み
      (require 'skk-leim)
      (setq default-input-method "japanese-skk")
      (require 'skk-autoloads)
      (require 'skk-cus)
    #+END_SRC
** emacs-w3m
   #+BEGIN_SRC emacs-lisp
     (when (locate-library "w3m-load")
       (my:org-babel-tangle-and-compile-file
        (concat my:user-emacs-config-directory "w3m_config.org"))
       (my:load-org-file "w3m_config.org"))
   #+END_SRC
** MUA
   Wanderlustを愛用中
   #+BEGIN_SRC emacs-lisp
     (cond
      ((string-match system-name "daphne")
       (my:load-org-file "wl_config.org"))
      (t
       (my:load-org-file "mew_config.org"))
      )
   #+END_SRC
** [[file:GUI.org][フォントとフレームの設定]]
   #+BEGIN_SRC emacs-lisp
   (my:load-org-file "frame_config.org")
   #+END_SRC
** [[file:lookup_config.org][lookup-elで電子辞書を引く設定]]
   #+BEGIN_SRC emacs-lisp
     (when (locate-library "lookup")
       (my:load-org-file "lookup_config.org"))
   #+END_SRC
** [[file:migemo_config.org][Migemoの設定]]
   #+BEGIN_SRC emacs-lisp
     (when (and (file-executable-p "/usr/bin/cmigemo")
                (locate-library "migemo"))
       (my:load-org-file "migemo_config.org"))
   #+END_SRC
** [[http://howm.sourceforge.jp/index-j.html][Howm]] - Hitori Otegaru Wiki Modoki
   無いと途方に暮れるので, 適宜最新版を site-lisp 以下に持つことに.
   #+BEGIN_SRC emacs-lisp
     (my:load-org-file "howm_config.org")
   #+END_SRC
** [[file:auto-install_config.org][auto-installとinstallしたelispの設定]]
   #+BEGIN_SRC emacs-lisp
     (my:load-org-file "auto-install_config.org")
   #+END_SRC
** [[http://tromey.com/elpa/install.html][ELPA]] [fn:9]
   Emacs24から標準添付される予定のEmacs Lisp Package Archive.
   auto-install とは異なり, パッケージのバージョン管理もしてくれる.
*** install
    elpa 自体は auto-install-el で導入することに
    #+BEGIN_EXAMPLE
      (unless (locate-library "package")
        (auto-install-from-url "http://repo.or.cz/w/emacs.git/blob_plain/1a0a666f941c99882093d7bd08ced15033bc3f0c:/lisp/emacs-lisp/package.el"))
    #+END_EXAMPLE
    これが実行されると ~/.emacs.d/init.el に設定が追記されるので
    適宜修正しておくこと
*** 設定
    リポジトリとして [[http://marmalade-repo.org/][Marmalade]] [fn:10]も追加しておく
    #+BEGIN_SRC emacs-lisp
      (require 'package)
      (add-to-list 'package-archives
                   '("marmalade" . "http://marmalade-repo.org/packages/"))
      (package-initialize)
    #+END_SRC
** AUCTeX
   Debianのパッケージが無い場合には ELPA で導入しておくこと
   #+BEGIN_SRC emacs-lisp
     (when (locate-library "auctex")
       (my:load-org-file "auctex_config.org"))
   #+END_SRC
** Anything
   Debianでは[[http://packages.qa.debian.org/a/anything-el.html][anything-el]] [fn:11] としてパッケージ化されている.
   パッケージが使えない場合には
   ELPA で anything と anything-config を導入しておく
   (auto-install-batch の方が良いのか?).
   #+BEGIN_SRC emacs-lisp
     (when (locate-library "anything-config")
       (my:load-org-file "anything_config.org"))
   #+END_SRC
** auto-complete
   詳細は [[http://cx4a.org/software/auto-complete/index.ja.html][Auto Complete Mode]] [fn:12] 参照のこと.
   Debianでは[[http://packages.qa.debian.org/a/auto-complete-el.html][ auto-complete-el]] [fn:13] としてパッケージ化されている.
   パッケージが無い場合には ELPA で導入すること
   #+BEGIN_SRC emacs-lisp
     (when (locate-library "auto-complete-config")
       (my:load-org-file "auto-complete_config.org"))
   #+END_SRC
** yasnippets
   詳細は [[http://yasnippet-doc-jp.googlecode.com/svn/trunk/doc-jp/index.html][Yet Another Snippet extension]] [fn:14] 参照のこと.
   Debianでは [[http://packages.qa.debian.org/y/yasnippet.html][yasnippet]] [fn:15] としてパッケージ化されている.
   パッケージが無い場合には ELPA で導入すること
   #+BEGIN_SRC emacs-lisp
     (when (locate-library "yasnippet")
       (my:load-org-file "yasnippet_config.org"))
   #+END_SRC
* Footnotes

[fn:1] バッドノウハウと奥が深い症候群: [[http://0xcc.net/misc/bad-knowhow.html]]

[fn:2] Emacs23 日本語向け設定例: [[http://nijino.homelinux.net/emacs/emacs23-ja.html]]

[fn:3] Wanderlustと文字コード: [[http://d.hatena.ne.jp/kiwanami/20091103/1257243524]]

[fn:4] 鬼軍曹.el: [[https://github.com/k1LoW/emacs-drill-instructor/wiki/]]

[fn:5] mode-line-formatをダイエットさす: [[http://homepage1.nifty.com/blankspace/emacs/mode-line.html]]

[fn:6] customizing the mode-line: [[http://emacs-fu.blogspot.jp/2011/08/customizing-mode-line.html]]

[fn:7] 無駄な行末の空白を削除する(Emacs Advent Calendar jp:2010): [[http://d.hatena.ne.jp/tototoshi/20101202/1291289625]]

[fn:8] APEL: [[http://www.kanji.zinbun.kyoto-u.ac.jp/~tomo/elisp/APEL/index.html]]

[fn:9] ELPA: [[http://tromey.com/elpa/install.html]]

[fn:10] Marmalade: [[http://marmalade-repo.org/]]

[fn:11] anything-el - Debian PTS: [[http://packages.qa.debian.org/a/anything-el.html]]

[fn:12] Auto Complete Mode: [[http://cx4a.org/software/auto-complete/index.ja.html]]

[fn:13] auto-complete-el - Debian PTS: [[http://packages.qa.debian.org/a/auto-complete-el.html]]

[fn:14] Yet Another Snippet extension: [[http://yasnippet-doc-jp.googlecode.com/svn/trunk/doc-jp/index.html]]

[fn:15] yasnippet - Debian PTS: [[http://packages.qa.debian.org/y/yasnippet.html]]

[fn:16] align設定用例集: [[http://handlename.hatenablog.jp/entry/2011/12/11/214923]]
