# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#+TITLE: 言語の設定
#+AUTHOR: Youhei SASAKI
#+EMAIL: uwabami@gfd-dennou.org
#+DATE: 2016-08-01 11:01:51
#+LANG: ja
#+LAYOUT: page
#+CATEGORIES: cc-env emacs
#+PERMALINK: cc-env/emacs/config/language_config.html
* 始めに
  過去にはいろいろ設定していたのですが...
  - [[http://masutaka.net/chalow/2009-07-09-1.html][Emacs講座 -第7回- 文字コード / マスタカの ChangeLog メモ]]
  #+BEGIN_QUOTE
  いきなり矛盾しますが、最近の Emacs(例:23.3) では文字コードの設定は不要です。
  #+END_QUOTE
  ...え, そうなのか...

  というわけで OS 依存の条件分岐だけを記述しています．

  ちなみに
  =prefer-coding-system= を設定すると
  =default-file-name-coding-system= が設定されます．
  優先順位は以下の通り:
  1. =file-name-coding-system= を見る
  2. =file-name-coding-system= が nil なら =default-file-name-coding-system= を利用
* cp5022x.el
 Emacs23 から内部が Unicode ベースになっています．

 しかし文字コードの変換は GNU libc の iconv をベースにしているため，
 環境によっては文字の変換がうまく行なえません．
 そこで言語設定前に =cp5022x.el= をインストールすることにしています．
 #+BEGIN_SRC emacs-lisp
   (el-get-bundle awasira/cp5022x.el)
   (require 'cp5022x nil 'noerror)
 #+END_SRC
* East Asian Ambiguos 対応
  CJK 以外の East Asian Ambiguos，絵文字も2文字幅にするようにしています．
  #+BEGIN_SRC emacs-lisp
    (el-get-bundle eaw_and_emoji
      :type http
      :url "https://raw.githubusercontent.com/uwabami/locale-eaw-emoji/master/eaw_and_emoji.el")
    (require 'eaw_and_emoji nil 'noerror)
    (eaw-and-emoji-fullwidth)
    ;; (setq nobreak-char-display nil)
  #+END_SRC
* OSの違いに起因する条件分岐
  Mac と Linux では同じ Unicode でも正規化が異なります
  (具体的には Mac のファイルシステムである HFS+ では Unicode の正規化が異なります).
  Unicode の正規化と Mac OS X 特有の事情については
   - [[http://homepage1.nifty.com/nomenclator/unicode/normalization.htm][Unicode正規化とは]]
   - [[http://www.sakito.com/2010/05/mac-os-x-normalization.html][Mac OS X におけるファイル名に関するメモ(NFC, NFD等)]]
  等が参考になるでしょう.

  日本語のファイル名を扱うことは滅多にないものの,
  たまに祟りがあるのでそれを回避するための設定をしています.

  Windows の場合はファイル名などは cp932 にしているものの,
  最近 Windows 使っていないので良く知りません.
  #+BEGIN_SRC emacs-lisp
    ;; language and coding-system
    (cond
     ((eq system-type 'darwin)
      (require 'ucs-normalize)
      (set-file-name-coding-system 'utf-8-hfs)
      (setq locale-coding-system 'utf-8-hfs)
      ;; ついでにキーバインド: Ctrl を Mac から奪い取る
      (setq mac-pass-control-to-system t)
      ;; Cmd と Option を逆にする
      (setq ns-command-modifier 'meta)
      (setq ns-alternate-modifier 'super)
      (global-set-key [ns-drag-file] 'ns-find-file))
     ((eq system-type 'windows-nt)
      (set-file-name-coding-system 'cp932)
      (prefer-coding-system 'cp932)
      )
     (t
      ;; do nothing
      )
     )
  #+END_SRC
