# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#
# Copyright(C) Youhei SASAKI All rights reserved.
# $Lastupdate: 2013/07/08 19:34:24$
# License: Expat
#
#+TITLE: 言語の設定
#+AUTHOR: Youhei SASAKI
#+EMAIL: uwabami@gfd-dennou.org
#+SETUPFILE: ./export-config.org
#+BEGIN_HTML
---
layout: emacs
title: 言語の設定
---
#+END_HTML

* 始めに
  過去にはいろいろ設定していたのですが...

  - [[http://masutaka.net/chalow/2009-07-09-1.html][Emacs講座 -第7回- 文字コード / マスタカの ChangeLog メモ]] [fn:1]
  - [[http://www.m17n.org/mlarchive/mule-ja/201106/msg00005.html][mule-ja-2009:09813 Re: language-environment v.s. default-coding-system]] [fn:2]

  ...え, そうなの?

  というわけで OS 依存の条件分岐だけを記述しています.
* cp5022x

  Emacs23 から内部が Unicode ベースになっています.
  しかし文字コードの変換は GNU libc の iconv をベースにしているため,
  環境によっては文字の変換がうまく行なえません.

  そこで言語設定の前に =cp5022x.el= を読み込むことにしています.
  cp5022x については [[http://nijino.homelinux.net/emacs/emacs23-ja.html][Emacs23 日本語向け設定例]]  [fn:3] を参照して下さい.
  また, [[http://d.hatena.ne.jp/kiwanami/about][kiwanami]] さんが [[http://d.hatena.ne.jp/kiwanami/20091103/1257243524][Wanderlustと文字コード]] [fn:4]
  というエントリで素晴しい解説を書いて下さっています.
  #+BEGIN_SRC emacs-lisp
    (el-get 'sync '(cp5022x))
  #+END_SRC

* East Asian Ambiguos 対応

  CJK 以外の East Asian Ambiguos も2文字幅にするようにしています.
  #+BEGIN_SRC emacs-lisp
    (defun set-east-asian-ambiguous-width (width)
      (dolist (range
               '(#x00A1 #x00A4 (#x00A7 . #x00A8) #x00AA (#x00AD . #x00AE)
                        (#x00B0 . #x00B4) (#x00B6 . #x00BA) (#x00BC . #x00BF)
                        #x00C6 #x00D0 (#x00D7 . #x00D8) (#x00DE . #x00E1)
                        #x00E6 (#x00E8 . #x00EA) (#x00EC . #x00ED) #x00F0
                        (#x00F2 . #x00F3) (#x00F7 . #x00FA) #x00FC #x00FE
                        #x0101 #x0111 #x0113 #x011B (#x0126 . #x0127) #x012B
                        (#x0131 . #x0133) #x0138 (#x013F . #x0142) #x0144
                        (#x0148 . #x014B) #x014D (#x0152 . #x0153)
                        (#x0166 . #x0167) #x016B #x01CE #x01D0 #x01D2 #x01D4
                        #x01D6 #x01D8 #x01DA #x01DC #x0251 #x0261 #x02C4
                        #x02C7 (#x02C9 . #x02CB) #x02CD #x02D0
                        (#x02D8 . #x02DB) #x02DD #x02DF (#x0300 . #x036F)
                        (#x0391 . #x03A9) (#x03B1 . #x03C1) (#x03C3 . #x03C9)
                        #x0401 (#x0410 . #x044F) #x0451 #x2010
                        (#x2013 . #x2016) (#x2018 . #x2019) (#x201C . #x201D)
                        (#x2020 . #x2022) (#x2024 . #x2027) #x2030
                        (#x2032 . #x2033) #x2035 #x203B #x203E #x2074 #x207F
                        (#x2081 . #x2084) #x20AC #x2103 #x2105 #x2109 #x2113
                        #x2116 (#x2121 . #x2122) #x2126 #x212B
                        (#x2153 . #x2154) (#x215B . #x215E) (#x2160 . #x216B)
                        (#x2170 . #x2179) (#x2190 . #x2199) (#x21B8 . #x21B9)
                        #x21D2 #x21D4 #x21E7 #x2200 (#x2202 . #x2203)
                        (#x2207 . #x2208) #x220B #x220F #x2211 #x2215 #x221A
                        (#x221D . #x2220) #x2223 #x2225 (#x2227 . #x222C)
                        #x222E (#x2234 . #x2237) (#x223C . #x223D) #x2248
                        #x224C #x2252 (#x2260 . #x2261) (#x2264 . #x2267)
                        (#x226A . #x226B) (#x226E . #x226F) (#x2282 . #x2283)
                        (#x2286 . #x2287) #x2295 #x2299 #x22A5 #x22BF #x2312
                        (#x2460 . #x24E9) (#x24EB . #x254B) (#x2550 . #x2573)
                        (#x2580 . #x258F) (#x2592 . #x2595) (#x25A0 . #x25A1)
                        (#x25A3 . #x25A9) (#x25B2 . #x25B3) (#x25B6 . #x25B7)
                        (#x25BC . #x25BD) (#x25C0 . #x25C1) (#x25C6 . #x25C8)
                        #x25CB (#x25CE . #x25D1) (#x25E2 . #x25E5) #x25EF
                        (#x2605 . #x2606) #x2609 (#x260E . #x260F)
                        (#x2614 . #x2615) #x261C #x261E #x2640 #x2642
                        (#x2660 . #x2661) (#x2663 . #x2665) (#x2667 . #x266A)
                        (#x266C . #x266D) #x266F #x273D (#x2776 . #x277F)
                        (#xE000 . #xF8FF) (#xFE00 . #xFE0F) #xFFFD ))
        (set-char-table-range char-width-table range width))
      (set-char-table-range char-width-table #x00AC 1))
    (set-east-asian-ambiguous-width 2)
  #+END_SRC
* OSの違いに起因する条件分岐

  Mac と Linux では同じ Unicode でも正規化が異なります
  (具体的には Mac のファイルシステムである HFS+ では Unicode の正規化が異なります).
  Unicode の正規化と Mac OS X 特有の事情については
   - [[http://homepage1.nifty.com/nomenclator/unicode/normalization.htm][Unicode正規化とは]] [fn:5]
   - [[http://www.sakito.com/2010/05/mac-os-x-normalization.html][Mac OS X におけるファイル名に関するメモ(NFC, NFD等)]] [fn:6]
  等が参考になるでしょう.

  日本語のファイル名を扱うことは滅多にないものの,
  たまに祟りがあるのでそれを回避するための設定をしています.

  Windows の場合はファイル名などは cp932 にしているものの,
  最近 Windows 使っていないので良く知りません.
  #+BEGIN_SRC emacs-lisp
    (cond
     (darwin-p
      (require 'ucs-normalize)
      (setq file-name-coding-system 'utf-8-hfs)
      (setq locale-coding-system 'utf-8-hfs)
      ;; ついでにキーバインド: Ctrl を Mac から奪い取る
      (setq mac-pass-control-to-system t)
      ;; Cmd と Option を逆にする
      (setq ns-command-modifier 'meta)
      (setq ns-alternate-modifier 'super)
      (global-set-key [ns-drag-file] 'ns-find-file))
     (nt-p
      (setq file-name-coding-system 'cp932)
      (setq locale-coding-system 'cp932))
     (t
      (setq file-name-coding-system 'utf-8)
      (setq locale-coding-system 'utf-8))
    )
  #+END_SRC
** 補足
   =prefer-coding-system= を設定すると
   =default-file-name-coding-system= が設定される.
   優先順位は
   1. =file-name-coding-system= を見る
   2. =file-name-coding-system=  が nil なら =default-file-name-coding-system= を利用
   となっている。

   =darwin-p= と =nt-p= は =~/.emacs.d/init.el= ([[http://www.gfd-dennou.org/member/uwabami/cc-env/EmacsBasic.html][解説]])
   で設定した環境判定用の以下の変数:
   #+BEGIN_EXAMPLE
   (defvar darwin-p (eq system-type 'darwin))      ; Mac OS X 用
   (defvar nt-p (eq system-type 'windows-nt))      ; Windows 用
   #+END_EXAMPLE
* Footnotes

[fn:1] Emacs講座 -第7回- 文字コード / マスタカの ChangeLog メモ:  [[http://masutaka.net/chalow/2009-07-09-1.html]]

[fn:2] mule-ja-2009:09813 Re: language-environment v.s. default-coding-system: [[http://www.m17n.org/mlarchive/mule-ja/201106/msg00005.html]]

[fn:3] Emacs23 日本語向け設定例: [[http://nijino.homelinux.net/emacs/emacs23-ja.html]]

[fn:4] Wanderlustと文字コード: [[http://d.hatena.ne.jp/kiwanami/20091103/1257243524]]

[fn:5] Unicode正規化とは: [[http://homepage1.nifty.com/nomenclator/unicode/normalization.htm]]

[fn:6] Mac OS X におけるファイル名に関するメモ(NFC, NFD等): [[http://www.sakito.com/2010/05/mac-os-x-normalization.html]]
