# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#
# Copyright(C) Youhei SASAKI <uwabami@gfd-dennou.org> All rights reserved.
# $Lastupdate: 2013/01/24 19:43:29$
# License: Expat
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#+AUTHOR: Youhei SASAKI
#+EMAIL:  uwabami@gfd-dennou.org
#+TITLE: navi2ch の設定
#+BEGIN_HTML
---
layout: emacs
title: navi2chの設定
---
#+END_HTML
* 始めに
  本家 [[http://navi2ch.sourceforge.net/index.ja.html][Navi2ch Project Home Page]] より
  #+BEGIN_QUOTE
  Navi2ch は、Emacs、XEmacs、Meadow などの Emacsen で動作する、
  ２ちゃんねるナビゲータです。
  #+END_QUOTE
* install
  bundle で install
  #+BEGIN_SRC emacs-lisp
    (unless (locate-library "navi2ch")
       (bundle navi2ch))
  #+END_SRC
* 読み込み
  #+BEGIN_SRC emacs-lisp
    (autoload 'navi2ch "navi2ch" "Navigator for 2ch for Emacs" t)
  #+END_SRC
* ディレクトリ/設定ファイルの変更
 #+BEGIN_SRC emacs-lisp
   (setq navi2ch-directory my:user-emacs-temporary-directory
         navi2ch-init-file (concat my:user-emacs-config-directory "navi2ch_config")
         )
 #+END_SRC
* proxy
  #+BEGIN_SRC emacs-lisp
    (if (getenv "http_proxy")
        (setq navi2ch-net-http-proxy
              (replace-regexp-in-string "http://" "" (getenv "http_proxy"))))
  #+END_SRC
* 表示範囲
  #+BEGIN_SRC emacs-lisp
    (setq navi2ch-article-auto-range nil)
  #+END_SRC
* 検索結果の統合
  #+BEGIN_SRC emacs-lisp
    (eval-after-load "navi2ch"
      '(progn
         (setq navi2ch-search-web-search-method 'navi2ch-search-union-method)
         (setq navi2ch-search-union-method-list '(navi2ch-search-find-2ch-method
                                                  navi2ch-search-hula-method))
         ))
  #+END_SRC
* 送信控えを取る
  #+BEGIN_SRC emacs-lisp
    (eval-after-load "navi2ch"
        '(progn
           (setq navi2ch-message-save-sendlog t)
           (add-to-list 'navi2ch-list-navi2ch-category-alist
                        navi2ch-message-sendlog-board)
           (setq navi2ch-message-sendlog-message-format-function
                 'navi2ch-message-sendlog-message-format-with-board-name)
           ))
  #+END_SRC
* モナーフォント?
  #+BEGIN_SRC emacs-lisp
    (when window-system
      (eval-after-load "navi2ch"
        '(progn
           (set-face-attribute 'navi2ch-article-face nil :family "Monapo")
           (aput 'face-font-rescale-alist '((".*Monapo.*" 1.2)))
           )))
  #+END_SRC
* ローカルルールの参照
  #+BEGIN_SRC emacs-lisp
    (eval-after-load "navi2ch"
      '(progn
         (require 'navi2ch-head)))
  #+END_SRC
