# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#
# Copyright(C) Youhei SASAKI <uwabami@gfd-dennou.org> All rights reserved.
# $Lastupdate: 2012/09/13 12:43:42$
# License: Expat
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#+AUTHOR: Youhei SASAKI
#+EMAIL:  uwabami@gfd-dennou.org
#+TITLE: Twittering-mode
#+BEGIN_HTML
---
title: Twittering-mode
layout: emacs
---
#+END_HTML
* 導入
  #+BEGIN_SRC emacs-lisp
    (unless (locate-library "twittering-mode")
      (el-get 'sync 'twittering-mode))
  #+END_SRC
* 設定
  #+BEGIN_SRC emacs-lisp
    (setq twittering-use-master-password t)
    (setq twittering-private-info-file
          (expand-file-name (concat (getenv "HOME") "/.dotfiles/.twittering-mode.gpg")))
    (setq twittering-initial-timeline-spec-string
          '(":home" ))
    (setq twittering-icon-mode t)
    ;; Show icons
    (setq twittering-timer-interval 300)
    ;; Update your timeline each 300 seconds (5 minutes)
    (add-hook 'twittering-new-tweets-hook
              (lambda ()
                (let ((n twittering-new-tweets-count))
                  (start-process "twittering-notify" nil "notify-send"
                                 "-i" "/usr/share/pixmaps/gnome-emacs.png"
                                 "New tweets"
                                 (format "You have %d new tweet%s"
                                         n (if (> n 1) "s" ""))))))
  #+END_SRC
